version: '3'
services:
  substrate:
    build: blockchain
    container_name: substrate
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
      - "5000:5000"
      - "6000:6000"
  test:
    build: ts-tests
    container_name: test
    tty: true
    stdin_open: true
    volumes:
      - ./ts-tests:/app
  operator:
    image: zksync/server
    container_name: operator
    tty: true
    stdin_open: true
    env_file:
      - ./env/operator.env
    volumes:
      - ./ts-tests/build:/contracts/build
    ports:
      - "3000:3000"
      - "3031:3031"
      - "3030:3030"
      - "8088:8088"
  prover:
    image: zksync/prover
    container_name: prover
    tty: true
    stdin_open: true
    environment:
      - PROVER_SECRET_AUTH=sample
      - ETH_NETWORK=localhost
      - PROVER_SERVER_PORT=8088
      - WITNESS_GENERATORS=2
      - IDLE_PROVERS=1
      - RUST_LOG="zksync_api=debug,zksync_core=debug,zksync_eth_sender=debug,zksync_witness_generator=debug,zksync_server=debug,zksync_prover=debug,dummy_prover=info,key_generator=info,zksync_data_restore=info,zksync_eth_client=info,zksync_storage=info,zksync_state=info,zksync_types=info,exodus_test=info,loadtest=info,kube=debug,dev_ticker=info,block_sizes_test=info,zksync_config=debug"
  postgres:
    image: zksync/postgres
    container_name: postgres
    tty: true
    stdin_open: true
    ports:
      - "5432:5432"
    volumes:
      - ./test/config:/etc/tokens
  ticker:
    image: "matterlabs/dev-ticker:latest"
    container_name: ticker
    ports:
      - "9876:9876"
volumes:
  contracts:

