version: '3'
services:
  substrate:
    build: blockchain
    container_name: substrate
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
      - "5000:5000"
      - "6000:6000"
  test:
    build: ts-tests
    container_name: test
    tty: true
    stdin_open: true
    volumes:
      - ./ts-tests:/app
  watcher:
    build: watcher
    container_name: watcher
    tty: true
    stdin_open: true
    volumes:
      - /app/target
      - ./watcher:/app
volumes:
  contracts:

