version: '3'
services:
  substrate:
    build: blockchain
    container_name: substrate
    tty: true
    stdin_open: true
    ports:
      - "2000:2000"
      - "3000:3000"
      - "4000:4000"
  test:
    build: test
    container_name: test
    tty: true
    stdin_open: true
