version: '3'
services:
  operator:
    image: zksync/server
    container_name: operator
    tty: true
    stdin_open: true
    environment:
      - DATABASE_URL=postgres://postgres:password@localhost:5432/zksync
      - DB_POOL_SIZE=10
      - BLOCK_CHUNK_SIZES=6,30
      - WEB3_URL=http://127.0.0.1:8545
      - GENESIS_TX_HASH=0xb99ebfea46cbe05a21cd80fe5597d97b204befc52a16303f579c607dc1ac2e2e
      - CONTRACT_ADDR=0x70a0F165d6f8054d0d0CF8dFd4DD2005f0AF6B55
      - GOVERNANCE_ADDR=0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9
      - OPERATOR_FEE_ETH_ADDRESS=0x17a4dC4aF1FAF9c3Db0515a170491c37eb0373Dc
      - CONFIRMATIONS_FOR_ETH_EVENT=0
      - MAX_NUMBER_OF_WITHDRAWALS_PER_BLOCK=10
      - ETH_WATCH_POLL_INTERVAL=300
      - ETH_NETWORK=localhost
      - MINIBLOCKS_ITERATIONS=10
      - MINIBLOCK_ITERATION_INTERVAL=200
      - PROMETHEUS_EXPORT_PORT=3312
      - OPERATOR_COMMIT_ETH_ADDRESS=0x17a4dC4aF1FAF9c3Db0515a170491c37eb0373Dc
      - CHAIN_ID=9
      - GAS_PRICE_FACTOR=1
      - ETH_TX_POLL_PERIOD=3
      - ETH_EXPECTED_WAIT_TIME_BLOCK=30
      - ETH_WAIT_CONFIRMATIONS=1
      - ETH_MAX_TXS_IN_FLIGHT=3
      - ETH_IS_ENABLED=true
      - PROVER_SECRET_AUTH=sample
      - PROVER_PREPARE_DATA_INTERVAL=500
      - PROVER_HEARTBEAT_INTERVAL=1000
      - PROVER_CYCLE_WAIT=500
      - PROVER_GONE_TIMEOUT=60000
      - PROVER_SERVER_PORT=8088
      - WITNESS_GENERATORS=2
      - IDLE_PROVERS=1
      - FORCED_EXIT_MINIMUM_ACCOUNT_AGE_SECS=0
      - REST_API_PORT=3001
      - HTTP_RPC_API_PORT=3030
      - WS_API_PORT=3031
      - PRIVATE_CORE_SERVER_PORT=8090
      - PRIVATE_CORE_SERVER_URL=http://127.0.0.1:8090
      - API_REQUESTS_CACHES_SIZE=10000
    ports:
      - "3000:3000"
      - "3031:3031"
      - "3030:3030"
  prover:
    image: zksync/prover
    container_name: prover
    tty: true
    stdin_open: true
  postgres:
    image: zksync/postgres
    container_name: postgres
    tty: true
    stdin_open: true
    ports:
      - "5432:5432"