name: EVM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2020-08-29
    - name: Build
      run: cd blockchain && cargo build --verbose --all
    - name: Run tests
      run: cd blockchain && cargo test --verbose --all
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Copy rust target
      run: cp -r blockchain/target .
    - name: Install functional tests typescript
      run: cd zkrollup && npm install
    - name: Run functional tests
      run: cd zkrollup && npm run test
