name: EVM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test evm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build evm substrate chain and test contract
      run: docker build .
